pipeline {
    agent any

    environment {
        SERVER_IP = "18.144.238.204"
        SSH_USER = "ubuntu"
        DEPLOY_PATH = "/var/www/html"
        REPO = "https://github.com/divyesh2123/ExampleDeploymentofReact.git"
    }

    stages {

        stage('Clone Repository') {
            steps {
                git branch: 'main', url: "${REPO}"
            }
        }

        stage('Install Dependencies') {
            steps {
                dir('my-react-app') {
                    sh 'npm install'
                }
            }
        }

        stage('Build React App') {
            steps {
                dir('my-react-app') {
                    sh 'npm run build'
                }
            }
        }

        stage('Deploy to Apache Server') {
            steps {
                sh """
                ssh ${SSH_USER}@${SERVER_IP} '
                    sudo rm -rf /var/www/html/* &&
                    mkdir -p /tmp/react-build
                '

                scp -r my-react-app/dist/* ${SSH_USER}@${SERVER_IP}:/tmp/react-build/

                ssh ${SSH_USER}@${SERVER_IP} '
                    sudo cp -r /tmp/react-build/* /var/www/html/ &&
                    sudo rm -rf /tmp/react-build
                '
                """
            }
        }
    }

    post {
        success {
            echo "✅ Deployment Successful"
        }
        failure {
            echo "❌ Deployment Failed"
        }
    }
}